version: '3.8'

services:
  app:
    build: .
    container_name: mywebsite-app
    expose:
    - "5000"
    volumes:
    - ./app:/app
  
  nginx:
  image: nginx:latest
  container_name: mywebsite-nginx
  ports:
    - "80:80"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  depends_on: 
    - app