# docker-compose.ci.yaml
# This version uses the standard Docker Compose variable substitution format.
version: '3.8'
services:
  db:
    image: postgres:13
    container_name: test-db
    environment:
      POSTGRES_DB: mywebsite
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mywebsite"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: ${WEB_IMAGE}
    container_name: test-web
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: mywebsite
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

